import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { Navbar, Login, Footer } from "~/layouts";
import { OrderForm } from "~/layouts/Orders/OrderForm";

const Home: NextPage = () => {
  const { status } = useSession();
  const loggedIn = status !== "unauthenticated";

  return (
    <>
      <Head>
        <title>Crumbs Cookie Co.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {loggedIn ? (
          <>
            <Navbar />
            <OrderForm />
            <Footer />
          </>
        ) : (
          <Login />
        )}
      </main>
    </>
  );
};

export default Home;
